version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    target-branch: develop/v0.1.1
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [dependencies]
    ignore:
      - dependency-name: Microsoft.CodeAnalysis.CSharp
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: github-actions
    directory: /
    target-branch: develop/v0.1.1
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [dependencies]
    groups:
      github-actions:
        patterns: ["*"]
