<Project>
  <PropertyGroup>
    <VersionPrefix>0.1.1</VersionPrefix>
    <Version>$(VersionPrefix)</Version>
    <PackageVersion>$(VersionPrefix)</PackageVersion>
    <AssemblyVersion>$(VersionPrefix).0</AssemblyVersion>
    <FileVersion>$(VersionPrefix).0</FileVersion>
    <InformationalVersion>$(VersionPrefix)</InformationalVersion>
  </PropertyGroup>
</Project>
